removeCubes:function(positions){
    var x,y,z,
    i,f,b=0;
    for(i=0;i<positions.length;i+=3){
      x=positions[i];y=positions[i+1];z=positions[i+2];
      if(!this.type[x][y][z])continue;
      this.updateSums(x,y,z,-1);
      this.type[x][y][z]=0;
      var logic = this.logic[x][y][z],
      faceIndex=this.faceIndex[x][y][z];
      if((logic&1)){//-z
        b=faceIndex.pop();
        this.faceReplacement.push(b);
        this.clearFace(b);
      }
      if((logic&2)){//+z
        b=faceIndex.pop();
        this.faceReplacement.push(b);
        this.clearFace(b);
      }
      if((logic&4)){//-y
        b=faceIndex.pop();
        this.faceReplacement.push(b);
        this.clearFace(b);
      }
      if((logic&8)){//+y
        b=faceIndex.pop();
        this.faceReplacement.push(b);
        this.clearFace(b);
      }
      if((logic&16)){//-x
        b=faceIndex.pop();
        this.faceReplacement.push(b);
        this.clearFace(b);
      }
      if((logic&32)){//+x
        b=faceIndex.pop();
        this.faceReplacement.push(b);
        this.clearFace(b);
      }
    }
    for(i=0;i<positions.length;i+=3){
      x=positions[i];y=positions[i+1];z=positions[i+2];
      var type=this.type,typex=type[x],typexy=type[x][y],
          a=typex[y-1],b=typex[y+1],c=type[x-1],d=type[x+1];
      
      if(typexy[z-1]){
        f=this.faceReplacement.pop();
        if(f)
          this.drawZP(x,y,z-1,f);
        else
          this.addZP(x,y,z-1);
      }
      if(typexy[z+1]){
        f=this.faceReplacement.pop();
        if(f)
          this.drawZM(x,y,z+1,f);
        else
          this.addZM(x,y,z+1);
      }
      if(a&&a[z]){
        f=this.faceReplacement.pop();
        if(f)
          this.drawYP(x,y-1,z,f);
        else
          this.addYP(x,y-1,z);
      }
      if(b&&b[z]){
        f=this.faceReplacement.pop();
        if(f)
          this.drawYM(x,y+1,z,f);
        else
          this.addYM(x,y+1,z);
      }
      if(c&&c[y][z]){
        f=this.faceReplacement.pop();
        if(f)
          this.drawXP(x-1,y,z,f);
        else
          this.addXP(x-1,y,z);
      }
      if(d&&d[y][z]){
        f=this.faceReplacement.pop();
        if(f)
          this.drawXM(x+1,y,z,f);
        else
          this.addXM(x+1,y,z);
      }
    }
  },